# Generated by Django 4.1.3 on 2023-01-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_table_cloned_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="original_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
