# Generated by Django 4.1.3 on 2023-02-03 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_snapshot_remove_action_column_table_original_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="action",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="action",
            name="snapshot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.snapshot",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="parameters",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="action",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.table"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="action",
            unique_together={("table", "order")},
        ),
        migrations.RemoveField(
            model_name="action",
            name="extra_data",
        ),
        migrations.RemoveField(
            model_name="action",
            name="snapshot_version",
        ),
        migrations.RemoveField(
            model_name="action",
            name="type",
        ),
    ]
