# Generated by Django 4.1.3 on 2023-01-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="snapshot",
            name="column_stats",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="snapshot",
            name="version",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
