# Generated by Django 4.1.3 on 2023-02-16 08:32

import apps.core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0006_action_parameters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="cloned_from",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.table",
            ),
        ),
        migrations.CreateModel(
            name="Join",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "join_type",
                    models.CharField(
                        choices=[
                            ("inner_join", "Inner Join"),
                            ("outer_join", "Outer Join"),
                            ("left_join", "Left Join"),
                            ("right_join", "Right Join"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "clauses",
                    models.JSONField(
                        default=list,
                        validators=[apps.core.validators.validate_join_clauses],
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_sources",
                        to="core.table",
                    ),
                ),
                (
                    "target_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_targets",
                        to="core.table",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="table",
            name="joined_from",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.join",
            ),
        ),
    ]
