# Generated by Django 4.1.3 on 2022-12-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="file_size",
            field=models.PositiveIntegerField(default=0, verbose_name="File size"),
            preserve_default=False,
        ),
    ]
